import Head from 'next/head'
import { Inter } from 'next/font/google'
import { Box, ContentContainer, Text } from '../atoms'
import { Carousel, Colors } from '../organisms'
import { SectionAbout, SectionDevelopment, SectionProjects } from '../organisms/sections'
import { Footer } from '../organisms/layout/footer'
import { useAppContext } from '../context/AppContext'
import { useState } from 'react'
import { Banner } from '../organisms/banner/banner'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

   const { dataImages } = useAppContext()

   return (
      <>
         <Head>
            <title>MF Planejados</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
            <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
            <link rel="icon" href="/logo.png" />
         </Head>
         <Box fullWidth sx={styles.container}>
            <Box fullWidth sx={styles.containerSection}>
               <Box sx={{ display: 'flex', width: '100%', }}>
                  <ContentContainer row fullWidth style={{ height: { xs: 'auto', xm: 480, md: 480, lg: 480 }, flexDirection: { xs: `column`, xm: 'row', md: 'row', lg: 'row' }, boxShadow: { xs: `none`, } }} gap={0}>
                     <Box sx={{
                        display: 'flex',
                        flexDirection: 'column',
                        justifyContent: 'center',
                        alignItems: 'center',
                        width: '100%',
                        height: '100%',
                        flex: 1,
                        gap: 1
                     }}>
                        <Box sx={{
                           ...styles.icon,
                           backgroundImage: `url('/logo.png')`,
                           backgroundSize: 'contain',
                           // marginRight: 10,
                           justifyContent: 'center',
                           alignItems: 'center',
                           backgroundRepeat: 'no-repeat',
                           height: 123,
                           width: 250,
                           left: 0,
                           display: { xs: 'none', xm: 'flex', md: 'flex', lg: 'flex' }
                        }} onClick={() => router.push('/')} />

                        <Box sx={{ display: 'flex', width: { xs: `100%`, xm: '60%', md: '60%', lg: '60%' }, marginTop: 5, alignItems: 'center', justifyContent: 'center' }}>
                           <Text title bold style={{ color: Colors.darkRed, textAlign: 'center' }}>FAÇA SEU ORÇAMENTO  <Text title > E TENHA SEU SONHO PLANEJADO</Text> DO SEU JEITO</Text>
                        </Box>
                        <Box sx={{ display: 'flex', width: { xs: `100%`, xm: '60%', md: '60%', lg: '60%' }, marginTop: 2, alignItems: 'center', justifyContent: 'center' }}>
                           <Text small bold style={{ color: Colors.darkBlue, textAlign: 'center' }}>Compromisso, confiança e agilidade. <Text small>Quem não gostaria de planejar os moveis de casa sob medida?</Text></Text>
                        </Box>
                     </Box>

                     <Banner data={dataImages} />
                  </ContentContainer>
               </Box>
            </Box>

            <Box sx={{
               height: '300px',
            }}>
               <Carousel data={dataImages} />
            </Box>

            <SectionAbout data={dataImages} />

            <Box sx={{
               height: { xs: `auto`, xm: '600px', md: '600px', lg: '600px' },
               marginBottom: { xs: `100px`, xm: '0px', md: '0px', lg: '0px' }
            }}>
               <SectionDevelopment />
            </Box>

            <Box sx={{
               height: 'auto',
               marginBottom: 10
            }}>
               <SectionProjects data={dataImages} />
            </Box>
            <Footer />
         </Box>
      </>
   )
}

const styles = {
   container: {
      // backgroundColor: '#fff',
      flex: 1
   },
   containerSection: {
      backgroundColor: '#fff',
      // display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      top: 10,
      left: 0,
      width: '100%',
      height: 'auto'
   },
   textHeader: {
      color: '#fff'
   },

}
